var location = {
    ancestorOrigins: {length: 0},
    assign: function assign(){console.log("调用了assign")},
    hash: "",
    host: "www.xxx.com",
    hostname: "www.xxx.com",
    href: "https://www.xxx.com/",
    origin: "https://www.xxx.com",
    pathname: "/",
    port: "",
    protocol: "https:",
    reload: function reload(){console.log("调用了reload")},
    replace: function replace(){console.log("调用了replace")},
    search: "",
}